<%' FP_ASP ASP Automatically generated by a FrontPage Component. Do not Edit.

On Error Resume Next
Session("FP_OldCodePage") = Session.CodePage
Session("FP_OldLCID") = Session.LCID
Session.CodePage = 65001
Err.Clear

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("newSQL_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "OxfordSchool", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(10)
	Dim arFormDBFields0(10)
	Dim arFormValues0(10)

	arFormFields0(0) = "Telephone"
	arFormDBFields0(0) = "Telephone"
	arFormValues0(0) = Request("Telephone")
	arFormFields0(1) = "Diet"
	arFormDBFields0(1) = "Diet_Reqs"
	arFormValues0(1) = Request("Diet")
	arFormFields0(2) = "Reason"
	arFormDBFields0(2) = "Reason"
	arFormValues0(2) = Request("Reason")
	arFormFields0(3) = "Access"
	arFormDBFields0(3) = "Access_Reqs"
	arFormValues0(3) = Request("Access")
	arFormFields0(4) = "Institution"
	arFormDBFields0(4) = "Institution"
	arFormValues0(4) = Request("Institution")
	arFormFields0(5) = "email"
	arFormDBFields0(5) = "Email"
	arFormValues0(5) = Request("email")
	arFormFields0(6) = "ScientificSubject"
	arFormDBFields0(6) = "Scientific_Subject"
	arFormValues0(6) = Request("ScientificSubject")
	arFormFields0(7) = "Name"
	arFormDBFields0(7) = "Name"
	arFormValues0(7) = Request("Name")
	arFormFields0(8) = "Address"
	arFormDBFields0(8) = "Address"
	arFormValues0(8) = Request("Address")
	arFormFields0(9) = "Comments"
	arFormDBFields0(9) = "Comments"
	arFormValues0(9) = Request("Comments")

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0

	FP_SaveFieldToDB fp_rs, Now, "timestamp"

	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	Session("FP_SavedFields")=arFormFields0
	Session("FP_SavedValues")=arFormValues0
	Session.CodePage = Session("FP_OldCodePage")
	Session.LCID = Session("FP_OldLCID")
	Response.Redirect "thanks.asp"

End If
End If

Session.CodePage = Session("FP_OldCodePage")
Session.LCID = Session("FP_OldLCID")

%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en-gb">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="keywords" content="neutron scattering, neutron, 12th oxford summer school, neutron spectroscopy, neutron diffraction, neutron training course, pre-registration">
<meta name="description" content="Registration for the 12th Oxford School on Neutron Scattering">

<title>Registration | 12th Oxford School on Neutron Scattering, 5-16 September 2011</title>
<link rel="stylesheet" type="text/css" href="../osns.css">
</head>

<body>

<div class="main" align="center">

    <h1>
    12th Oxford School on Neutron Scattering</h1>

      <h2 class="left">5-16 September 2011</h2>
      
      <h2 class="left"><font color="#000080">University of Oxford</font></h2>

	<form method="POST" action="osns2011registration.asp" webbot-action="--WEBBOT-SELF--">
  <!--webbot bot="SaveDatabase" U-ASP-Include-Url="../_fpclass/fpdbform.inc" startspan SuggestedExt="asp" S-DataConnection="newSQL" S-RecordSource="OxfordSchool" S-Form-Fields="Telephone Diet Reason Access Institution email ScientificSubject Name Address Comments" S-Form-DBFields="Telephone Diet_Reqs Reason Access_Reqs Institution Email Scientific_Subject Name Address Comments" U-Confirmation-Url="thanks.asp" S-Builtin-Fields="Timestamp" S-Builtin-DBFields="timestamp" --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../_fpclass/fpdbform.inc"--><!--webbot bot="SaveDatabase" endspan i-checksum="34604" -->
  <h3>Registration</h3>
	<p><b>Welcome to the Registration area for the 12th Oxford School on Neutron 
	Scattering.</b></p>
  <h3><b>If you wish to re-register for the 
  11th Oxford School on Neutron Scattering, <br>
	please submit this form by 23:30 BST 17 June 2009.</b></h3>
	<p>You will be notified if you have been successful with your application by 
	26 June 2009.</p>
	<p>If you have any questions about filling in this form, please contact us 
	at <a href="mailto:osns@stfc.ac.uk">osns@stfc.ac.uk</a>.</p>
	<p>As additional safety, we would be grateful if you could also email your 
	submissions to <a href="mailto:osns@stfc.ac.uk">osns@stfc.ac.uk</a> .</p>
  <hr>
  <table border="0" width="100%" cellspacing="4" style="border-collapse: collapse" bordercolor="#111111" cellpadding="0">
    <tr>
      <td width="110%" style="vertical-align: middle">
      <h4>Your name<br>
      <input type="text" name="Name" size="91"></h4>
      <h4>Your institution<br>
		<input type="text" name="Institution" size="91"></h4>
      <h4>Your address<br>
		<textarea rows="5" name="Address" cols="60"></textarea></h4>
      <h4>Your telephone<br>
      <input type="text" name="Telephone" size="91"></h4>
      <h4>Your email<br>
	<input type="text" name="email" size="91"></h4>
      <h4>Your scientific subject<br>
		<input type="text" name="ScientificSubject" size="91"></h4>
      <hr>
      <h4>Selection statement</h4>
      <p>Competition for places at the Oxford School on Neutron Scattering is 
		intense. Typically we receive three applications 
		for every place. To help us with the selection process, please tell us 
		<b>in English</b> <b>in no more than 200 words</b> 
		how your studies would benefit by you attending the School. Note that 
		those who complete this section of the application are always ranked 
		higher than those who do not.<p>
		<textarea rows="5" name="Reason" cols="80"></textarea><hr>
      <h4>Academic supervisor</h4>
      <p><span style="vertical-align: middle">We require contact information and 
		a supporting statement from for your academic supervisor. The supporting 
		statement is used in the selection process. </span></p>
		<h4>Supervisor name<br>
      <input type="text" name="supervisorName" size="91"></h4>
      <h4>Supervisor institution<br>
		<input type="text" name="supervisorInstitution" size="91"></h4>
      <h4>Supervisor address<br>
		<textarea rows="5" name="supervisorAddress" cols="60"></textarea></h4>
      <h4>Supervisor telephone<br>
      <input type="text" name="supervisorTelephone" size="91"></h4>
      <h4>Supervisor email<br>
	<input type="text" name="supervisoremail" size="91"></h4>
      <h4>Supervisor supporting statement</h4>
      <p>Please tell us 
		<b>in English</b> <b>in no more than 200 words</b> 
		how the applicant will benefit from attending the School. <p>
		<textarea rows="5" name="supervisorReason" cols="80"></textarea><hr>
      <h4>Diet 
      requirements:</h4>
      <p>Breakfast and evening meals are provided 
		at the School. We can cater for most diets, 
      including vegetarian, vegan and gluten-free, but we do need to give advance notice 
		to the kitchens, so please tell us here if you have any specific 
		requirements for your food.</p>
      <p>If you can no special requirements, please type &#39;None&#39; in the box.</p>
      <p>
		<textarea rows="5" name="Diet" cols="80"></textarea><hr>
      <h4>Access requirements:</h4>
      <p>We can 
		provide bedrooms 
		with level ground-floor access, and there is level access into the 
		Lecture Theatres where the teaching sessions will take place. 
      Please tell us if you will need a ground-floor bedroom, or if there is 
      anything else that you will need (eg. large print lecture notes) in order 
      to get the most out of the Oxford School.</p>
      <p>If you don&#39;t have any access requirements, please type &#39;None&#39; in the 
      box.</p>
      <p>
		<textarea rows="5" name="Access" cols="80"></textarea></td>
    </tr>
    <tr>
      <td width="110%" style="vertical-align: middle">
      <hr>
      <h4>Any other comments?</h4>
      <p>If there is anything else that you think we should know, please tell us 
		here:<p>
		<textarea rows="5" name="Comments" cols="80"></textarea><p>&nbsp;</td>
    </tr>
  </table>
  <hr>
  <h3>Data Protection Act 1998</h3>
  <p>The personal data you supply here will be stored by ISIS on behalf of the Oxford School on Neutron 
  scattering and will be used to contact you with further information about the 
  School. You will have deemed to have given your consent to 
  this processing by submitting this registration form. We will only use your 
  information to deliver the service(s) you have requested, or for our lawful, 
  disclosed purposes. We will not make your personal details available outside 
  our organisation without your consent, unless obliged by law.</p>
  <p>
  <input type="submit" value="Submit registration form"> </p>
  <hr>
  <p><input type="reset" value="Reset form"></p>
  <hr>

	<!--webbot bot="Include" U-Include="../supported.htm" TAG="BODY" startspan -->

<p>Supported by</p>
<p>&nbsp;&nbsp; <a target="_blank" href="http://www.isis.stfc.ac.uk/"> 
<img alt="" src="../images/img11.jpg" class="style1" width="170" height="47"></a>&nbsp;&nbsp;
<a target="_blank" href="http://www2.physics.ox.ac.uk/">
<img alt="" src="../images/logo.png" width="158" height="49" class="style1"></a>&nbsp;
<a target="_blank" href="http://www.sine2020.eu/">
<img alt="" src="../images/sine2020.png" width="113" height="54" class="style1"></a>&nbsp;
<a target="_blank" href="http://www.iop.org/">
<img alt="" src="../images/iop.png" width="113" height="54" class="style1"></a>&nbsp;
<a target="_blank" href="http://www.ill.eu/"> 
<img alt="" src="../images/img10.jpg" width="64" height="58" class="style1"></a>&nbsp;&nbsp;&nbsp;&nbsp;


<!--webbot bot="Include" i-checksum="61839" endspan --><hr>
      <p>
      Last updated:
      <!--webbot bot="Timestamp" S-Type="EDITED" S-Format="%A, %d %B %Y %H:%M" startspan -->Thursday, 19 January 2017 15:29<!--webbot bot="Timestamp" i-checksum="6906" endspan --></p>
      <!--webbot bot="Include" U-Include="../hosted.htm" TAG="BODY" startspan -->

<p>The Oxford School on Neutron Scattering website is hosted by 
<a href="http://www.isis.stfc.ac.uk">ISIS</a> 
      at the Rutherford Appleton Laboratory.</p>

<!--webbot bot="Include" i-checksum="52342" endspan --><hr>

</form>
</div>
</body>

</html>